In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('dataset.csv')
df

      business_code cust_number  ...    invoice_id isOpen
0              U001  0200769623  ...  1.930438e+09      0
1              U001  0200980828  ...  1.929646e+09      0
2              U001  0200792734  ...  1.929874e+09      0
3              CA02  0140105686  ...  2.960623e+09      1
4              U001  0200769623  ...  1.930148e+09      0
...             ...         ...  ...           ...    ...
49995          U001  0200561861  ...  1.930797e+09      1
49996          U001  0200769623  ...  1.929744e+09      0
49997          U001  0200772595  ...  1.930537e+09      0
49998          U001  0200726979  ...  1.930199e+09      0
49999          U001  0200020431  ...  1.928576e+09      0

[50000 rows x 19 columns]

In [5]:
df.columns

Index(['business_code', 'cust_number', 'name_customer', 'clear_date',
       'buisness_year', 'doc_id', 'posting_date', 'document_create_date',
       'document_create_date.1', 'due_in_date', 'invoice_currency',
       'document type', 'posting_id', 'area_business', 'total_open_amount',
       'baseline_create_date', 'cust_payment_terms', 'invoice_id', 'isOpen'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   business_code           50000 non-null  object
 1   cust_number             50000 non-null  object
 2   name_customer           50000 non-null  object
 3   clear_date              40000 non-null  object
 4   buisness_year           50000 non-null  float64
 5   doc_id                  50000 non-null  float64
 6   posting_date            50000 non-null  object
 7   document_create_date    50000 non-null  int64
 8   document_create_date.1  50000 non-null  int64
 9   due_in_date             50000 non-null  float64
 10  invoice_currency        50000 non-null  object
 11  document type           50000 non-null  object
 12  posting_id              50000 non-null  float64
 13  area_business           0 non-null      float64
 14  total_open_amount       50000 non-null  float64
 15  baseline_create_date    50000 non-null  float64
 16  cust_payment_terms      50000 non-null  object
 17  invoice_id              49994 non-null  float64
 18  isOpen                  50000 non-null  int64
dtypes: float64(8), int64(3), object(8)
memory usage: 7.2+ MB

In [7]:
%%time
df.drop(columns=['area_business'], inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   business_code           50000 non-null  object
 1   cust_number             50000 non-null  object
 2   name_customer           50000 non-null  object
 3   clear_date              40000 non-null  object
 4   buisness_year           50000 non-null  float64
 5   doc_id                  50000 non-null  float64
 6   posting_date            50000 non-null  object
 7   document_create_date    50000 non-null  int64
 8   document_create_date.1  50000 non-null  int64
 9   due_in_date             50000 non-null  float64
 10  invoice_currency        50000 non-null  object
 11  document type           50000 non-null  object
 12  posting_id              50000 non-null  float64
 13  total_open_amount       50000 non-null  float64
 14  baseline_create_date    50000 non-null  float64
 15  cust_payment_terms      50000 non-null  object
 16  invoice_id              49994 non-null  float64
 17  isOpen                  50000 non-null  int64
dtypes: float64(7), int64(3), object(8)
memory usage: 6.9+ MB
CPU times: user 33.8 ms, sys: 18 Âµs, total: 33.8 ms
Wall time: 34.2 ms

In [8]:
from datetime import datetime

# print(datetime.strptime('0552019', '%d%m%Y'))
df['due_in_date'].apply(lambda x: datetime.strptime(str(int(x)), '%Y%m%d'))

0       2020-02-10
1       2019-08-11
2       2019-09-29
3       2020-04-10
4       2019-11-28
           ...
49995   2020-05-06
49996   2019-08-30
49997   2020-03-05
49998   2019-12-12
49999   2019-01-24
Name: due_in_date, Length: 50000, dtype: datetime64[ns]

In [9]:
df['due_in_date'] = df['due_in_date'].apply(lambda x: datetime.strptime(str(int(x)), '%Y%m%d'))
df

      business_code cust_number  ...    invoice_id isOpen
0              U001  0200769623  ...  1.930438e+09      0
1              U001  0200980828  ...  1.929646e+09      0
2              U001  0200792734  ...  1.929874e+09      0
3              CA02  0140105686  ...  2.960623e+09      1
4              U001  0200769623  ...  1.930148e+09      0
...             ...         ...  ...           ...    ...
49995          U001  0200561861  ...  1.930797e+09      1
49996          U001  0200769623  ...  1.929744e+09      0
49997          U001  0200772595  ...  1.930537e+09      0
49998          U001  0200726979  ...  1.930199e+09      0
49999          U001  0200020431  ...  1.928576e+09      0

[50000 rows x 18 columns]

In [10]:
type(df['clear_date'].iloc[0])

str

In [11]:
df['clear_date'] = df['clear_date'].apply(lambda x: str(x)[:10])

In [12]:
df

      business_code cust_number  ...    invoice_id isOpen
0              U001  0200769623  ...  1.930438e+09      0
1              U001  0200980828  ...  1.929646e+09      0
2              U001  0200792734  ...  1.929874e+09      0
3              CA02  0140105686  ...  2.960623e+09      1
4              U001  0200769623  ...  1.930148e+09      0
...             ...         ...  ...           ...    ...
49995          U001  0200561861  ...  1.930797e+09      1
49996          U001  0200769623  ...  1.929744e+09      0
49997          U001  0200772595  ...  1.930537e+09      0
49998          U001  0200726979  ...  1.930199e+09      0
49999          U001  0200020431  ...  1.928576e+09      0

[50000 rows x 18 columns]

In [13]:
df['difference'] = (pd.to_datetime(df['clear_date']) - pd.to_datetime(df['due_in_date']))
df['difference'] = df['difference'].apply(lambda x: x.days)

In [14]:
df

      business_code cust_number  ... isOpen difference
0              U001  0200769623  ...      0        1.0
1              U001  0200980828  ...      0       -3.0
2              U001  0200792734  ...      0       92.0
3              CA02  0140105686  ...      1        NaN
4              U001  0200769623  ...      0       -3.0
...             ...         ...  ...    ...        ...
49995          U001  0200561861  ...      1        NaN
49996          U001  0200769623  ...      0        4.0
49997          U001  0200772595  ...      0        0.0
49998          U001  0200726979  ...      0        0.0
49999          U001  0200020431  ...      0       -9.0

[50000 rows x 19 columns]

In [15]:
df['difference'] = df['difference'].apply(lambda x : 0 if x < 0 else x)

In [16]:
df

      business_code cust_number  ... isOpen difference
0              U001  0200769623  ...      0        1.0
1              U001  0200980828  ...      0        0.0
2              U001  0200792734  ...      0       92.0
3              CA02  0140105686  ...      1        NaN
4              U001  0200769623  ...      0        0.0
...             ...         ...  ...    ...        ...
49995          U001  0200561861  ...      1        NaN
49996          U001  0200769623  ...      0        4.0
49997          U001  0200772595  ...      0        0.0
49998          U001  0200726979  ...      0        0.0
49999          U001  0200020431  ...      0        0.0

[50000 rows x 19 columns]